<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SystemParams extends Model
{
    protected $fillable =[
        'SYS_APP_NAME', 'SYS_APP_NAME', 'SYS_APP_COMPANY', 'SYS_SMTP_SERVER', 'SYS_SMTP_USERNAME', 'SYS_SMTP_PASSWORD', 'SYS_TTR_MIN', 'SYS_TTR_MAX', 'SYS_WEEK_START', 'SYS_WEEK_END', 'SYS_DAY_START', 'SYS_DAY_END', 'SYS_PWD_LENGTH_MIN', 'SYS_PWD_NBR_REQ', 'SYS_PWD_SPE­CIAL_CHAR_REQ', 'SYS_PWD_UP­PER_CHAR_REQ', 'SYS_PWD_LOWER_CHAR_REQ', 'SYS_PWD_CHANGE_­DAYS_ACTUAL', 'SYS_FAILED_LOGIN_TRI­ALS_MAX', 'SYS_INACTIVITY_DAYS_­MAX'
    ];
}
